### ISSUE TITLE
How to use this module

### ISSUE THREAD

**Issue by ugintl** [nicksantamaria/drupal-vault#23]
Suppose there is a portal where clients upload some sensitive documents. Standard login is not an option. How can this module help me? or How should I use it?

**Comment by cmlara** [comment]
This module is basically a glue between a Hashicorp Vault php Library and Drupal  providing a Drupal Service that other modules can than call to connect to a Vault server.

Hashicorp vault in my experience tends to primarily provide storage for Auth Credentials and similar and less for full documents as there is a relatively small length restriction or objects, though one could use the Vault "Transit" provider where you feed binary data to vault it encrypts it and than sends it back to you to store on disk

If your not already using Hashicorp Vault this module will provide little to a Drupal environment.  If you are using vault than it will require some custom programing as I'm not aware of any modules that rely on this module at this time.
